services:
  shamrockseats:
    build: .
    image: piupiuson/shamrockseats:latest
    container_name: ShamrockSeats
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      PROXY_API_KEY: "${PROXY_API_KEY}"
